packageExtensions:
  ts-proto@*:
    dependencies:
      protobufjs: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-vcnc.cjs
    spec: plugin/bundles/@yarnpkg/plugin-vcnc.js
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
